# Generated by Django 3.2.6 on 2024-03-16 08:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chapter',
            name='description',
        ),
        migrations.AddField(
            model_name='chapter',
            name='content',
            field=models.FileField(blank=True, null=True, upload_to='chapters/'),
        ),
        migrations.AddField(
            model_name='chapter',
            name='content_type',
            field=models.CharField(choices=[('PDF', 'PDF'), ('TEXT', 'Text'), ('VIDEO', 'Video')], default='PDF', max_length=10),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='chapter',
            name='course',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chapters', to='courses.course'),
        ),
        migrations.DeleteModel(
            name='Content',
        ),
    ]
