# Generated by Django 3.2.6 on 2024-03-16 09:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0002_auto_20240316_1054'),
    ]

    operations = [
        migrations.AddField(
            model_name='chapter',
            name='description',
            field=models.TextField(default='PDF'),
            preserve_default=False,
        ),
    ]
